/*********************************************************************
 * version          Date        Name        Descriotion
 * ===================================================================
 *   v1.0         29-05-2025    Sai Sagar   Add Method Created
 *********************************************************************/
/********************************
 * Name : Calculator
 * Author : Pavan Kalyan Matcha
 * Date : 29-05-2025
 ********************************/

public with sharing class calcController {

    public calcController() {
        // From Develop branch
    }

    public Integer add(Integer a,Integer b){
        // From future/Add
        return a+b;
    }

    public Integer sub(Integer a,Integer b){
        // From future/sub
        return a-b;
    }
    
}