/*********************************************************************
 * version          Date        Name        Descriotion
 * ===================================================================
 *   v1.0         29-05-2025    Sagar     Created Class and cal Method
 *********************************************************************/

public with sharing class calcController {
    
    public calcController() {

    }
    
}